[nitpick.meta]
name = "EditorConfig"
url = "http://editorconfig.org/"

[".editorconfig"]
# top-most EditorConfig file
root = true

[".editorconfig"."*"]
# Unix-style newlines with a newline ending every file
end_of_line = "lf"
charset = "utf-8"
insert_final_newline = true
indent_style = "space"
indent_size = 4
max_line_length = "100"
ij_visual_guides = "80, 100"
# Whitespace at the end of lines
trim_trailing_whitespace = true

# Matches multiple files with brace expansion notation
# Set default charset
[".editorconfig"."{*.js,*json}"]
ij_visual_guides = "80, 100"
indent_size = 2

[".editorconfig"."{*.yaml,*.yml}"]
ij_visual_guides = "80, 100"
indent_size = 2

[".editorconfig".Makefile]
indent_style = "tab"

[".editorconfig"."{*.pyw,*.pyw}"]
ij_visual_guides = "80, 100"
