[nitpick.files.absent]
"requirements.txt" = "Install poetry, run 'poetry init' to create pyproject.toml, and move dependencies to it"
"Pipfile" = "Use pyproject.toml instead"
"Pipfile.lock" = "Use pyproject.toml instead"

[nitpick.files.present]
"pyproject.toml" = "Install poetry and run 'poetry init' to create it"
".editorconfig" = "A project should have an editor configuration"
"README.md" = "A project should have `README.md`"
".gitignore" = "A project should have `.gitignore` file"
